### ISSUE TITLE
exception in vs 2019.3

### ISSUE THREAD

**Issue by wushuyi** [Kir-Antipov/VisualDump#5]
Unhandled exception. System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at VisualDump.HTMLClients.PipeHTMLClient.WaitForConnection(Int32 TimeoutMS)
   at DumpExtensions.get_Client()
   at DumpExtensions.Dump[T](T Obj, String Header, Object[] Args, Assembly EntryAssembly)
   at DumpExtensions.Dump[T](T Obj, String Header)

**Comment by ethedy** [comment]
The same exception, in Visual Studio CE 2019 16.4.5

**Comment by Kira-NT** [comment]
Yeah, I know. I've lost an interest a little in this extension, as it turned out not that way I'd like to.

I want to completely rewrite this package soon :)

**Comment by areagu** [comment]
same exception...any updates ? :)

**Comment by Kira-NT** [comment]
@areagu, somebody's still interested in this extension, wow! No, I'm sorry, but there're no updates

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Please fix the issue. This extension is very useful! Thank you.

**Comment by Kira-NT** [comment]
@0x7FFFFFFFFFFFFFFF, welp, I'm really-really glad that people still find this extension useful. But there's one problem: I (just like any other developer) keep OS projects exactly as long as they bring me pleasure.  VisualDump, which I wrote almost two years ago, doesn't spark joy anymore. Like, seriously, what madman wrote this heck?

https://github.com/Kir-Antipov/VisualDump/blob/56d93f62f1a37256de5979dbdb14eae22b172056/DumpExtensions/HTMLProviders/DefaultProviders/DataTableHTMLProvider.cs#L20-L48

If I get my hands on VisualDump again, the first thing I'll do is rewrite it from scratch, since I just can't work with what my past self wrote. And this will take me quite a lot of [unpaid] time and [unpaid] effort. I think it's obvious why fixing the extension isn't on my top priority list right now.

I do realize that the idea of VisualDump is kinda cool, even if I don't like my old implementation, so, coupled with the fact that there're still people interested in this, it's very likely that I'll revive this extension again, but I don't know when I'll have spare time for this

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I totally understand! Don't rush and take your time. This is a great extension and I'm very interested in it.

**Comment by zhangzunke** [comment]
same exception, any updates?

**Comment by Kira-NT** [comment]
@zhangzunke, as I said in #7:

> VS 2022 is somewhere around the corner, so I might start rewriting my extensions soon
