### ISSUE TITLE
Either provide option to disable automatic add of DumpExtensions or allow it to operate within LINQPad

### ISSUE THREAD

**Issue by CyberBotX** [Kir-Antipov/VisualDump#7]
The subject line kinda says it all, but basically, I've run into the issue of getting an exception in LINQPad if I try to use `.Dump()` when DumpExtensions has been pulled in by an assembly of mine. Specifically, I get a `TypeInitializationException` with the message `The type initializer for 'DumpExtensions' threw an exception.` and an inner `NotSupportedException` with the message `The invoked member is not supported in a dynamic assembly.`. And this was caused because VisualDump automatically added DumpExtensions to my project.

The stack trace of the outer exception is:
```
   at DumpExtensions.Dump[T](T Obj)
   at UserQuery.Main(), line 11
   at UserQuery.Main(), line 29
```
And the stack trace of the inner exception is:
```
   at System.Reflection.Emit.InternalAssemblyBuilder.GetExportedTypes()
   at DumpExtensions.<>c.<.cctor>b__26_1(Assembly x)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at DumpExtensions..cctor()
```

So, either VisualDump needs an option to disable the automatic add of DumpExtensions to projects, or DumpExtensions needs to be able to detect that it is running within LINQPad and not get used (or just pass the call to LINQPad's version of Dump). Looking at the code, I do not know how the latter could be accomplished, so I think the former might be an easier thing to implement.

**Comment by Kira-NT** [comment]
Yeah, I know. There're a lot things I want to change, and this is one of them. VS 2022 is somewhere around the corner, so I might start rewriting my extensions soon
